"""add render_storage_key and rendered to clips

Revision ID: 9b90171115e1
Revises: b2c3d4e5f6a7
Create Date: 2026-08-06 03:18:11.045614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b90171115e1'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('render_storage_key', sa.String(length=512), nullable=True))
    op.add_column('clips', sa.Column('rendered', sa.Boolean(), nullable=True))
    # Set default for existing rows
    op.execute("UPDATE clips SET rendered = false WHERE rendered IS NULL")
    op.alter_column('clips', 'rendered', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'rendered')
    op.drop_column('clips', 'render_storage_key')
    # ### end Alembic commands ###
